--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Refaltor77/recurring-message
build-by-default: true
branches:
- main
projects:
  recurring-message:
    path: ""
    icon: icon.png
...
